name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: |
          echo "Hello World !"
          echo "testing multiple line command"
      - name: Print Goodbye
        run: echo "Goodbye!"
